name: Mirroring

on: [push, delete]

jobs:
  to_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1.1.0
        with:
          target_repo_url:
            git@github.com:illi99/TeamTable.git
          ssh_private_key:
            ${{ secrets.ILLI_REPO_SSH_PRIVATE_KEY }}
